name: inputs demo
on:
  workflow_dispatch: 
    inputs:
      environment:
        description:
        required: true
        default: dev
        options:
          - dev
          - test
          - prod
      artificat_tag:
        description: choose the tig tag to deploy type: 
        required: true
jobs:
  inputs-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Deply to dev
        run: echo "deplying to the ${{ inputs.artificat_tag}} application to ${{ inputs.environment }}"
